import type { Metadata } from "next";
import "./globals.css";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { getMessages } from "next-intl/server";
import type { ReactNode } from "react";
import Nav from "@/components/Nav/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const messages = await getMessages({ locale });
  return (
    <html lang="th">
      <body>
         <NextIntlClientProvider locale={locale} messages={messages}>
        {children}
        <div className="scrolledgeTop" />
        <Nav />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
